#!/usr/bin/env python3
"""One-off seed: turn the Flutter app's strings into L10n.swift + Localizable.xcstrings.

Usage: python3 scripts/seed_strings.py ../champz-mobile/lib/localization

After seeding, the catalog and L10n.swift are edited directly; this script is kept
for reference and is not meant to be re-run over hand edits.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
L10N_SWIFT = ROOT / "ChampzKit/Sources/Localization/L10n.swift"
XCSTRINGS = ROOT / "ChampzKit/Sources/Localization/Resources/Localizable.xcstrings"

SWIFT_KEYWORDS = {
    "continue", "default", "repeat", "in", "for", "while", "if", "else", "switch", "case", "return",
    "import", "class", "struct", "enum", "func", "var", "let", "self", "Self", "true", "false", "nil",
    "is", "as", "throw", "throws", "try", "catch", "do", "break", "where", "guard", "defer", "init",
    "deinit", "extension", "protocol", "public", "private", "internal", "static", "operator", "subscript",
    "typealias", "associatedtype", "inout", "Type", "Protocol", "any", "some",
}

SECTION_ENUM = {
    "General": "Common", "Onboarding": "Onboarding", "Auth / Login": "Auth", "Signup": "SignUp", "OTP": "Otp",
    "Forgot / Reset Password": "ResetPassword", "Profile": "Profile", "Home / Dashboard": "Home",
    "Tournament": "Tournament", "Team": "Team", "Transfer Market": "TransferMarket", "Payment": "Payment",
    "Notifications": "Notifications", "Court / Venue": "Court", "Social / Sharing": "Social", "Match": "Match",
    "Settings": "Settings", "Player": "Player", "Time": "Time", "Image Upload": "ImageUpload",
    "Content": "Content", "Friendly Match / Game Registration": "FriendlyMatch", "Rate limits": "RateLimits",
}

# Strings the iOS app needs that Flutter never had (tabs, generic error states).
IOS_ADDITIONS = {
    "Tabs": {
        "home": ("tabs.home", "Home"),
        "transferMarket": ("tabs.transfer_market", "Transfer Market"),
        "myStats": ("tabs.my_stats", "My Stats"),
    },
    "Errors": {
        "offlineTitle": ("errors.offline.title", "You're offline"),
        "offlineMessage": ("errors.offline.message", "Check your connection and try again."),
        "timeoutTitle": ("errors.timeout.title", "That took too long"),
        "timeoutMessage": ("errors.timeout.message", "The server didn't respond in time. Please try again."),
        "unauthorizedTitle": ("errors.unauthorized.title", "Session expired"),
        "unauthorizedMessage": ("errors.unauthorized.message", "Please sign in again."),
        "notFoundTitle": ("errors.not_found.title", "Not found"),
        "notFoundMessage": ("errors.not_found.message", "This item is no longer available."),
        "genericTitle": ("errors.generic.title", "Something went wrong"),
        "genericMessage": ("errors.generic.message", "Please try again in a moment."),
        "retry": ("errors.retry", "Try again"),
        "emptyTitle": ("errors.empty.title", "Nothing here yet"),
    },
}


def load_keys(locale_keys: str) -> dict[str, str]:
    return dict(re.findall(r"static const String (\w+) = '([^']+)';", locale_keys))


def parse_strings(app_string: str, keys: dict[str, str]):
    en_start = app_string.index('"en"')
    body = app_string[en_start:]
    sections: dict[str, list[tuple[str, str, str]]] = {}
    current = "General"
    token = re.compile(
        r"//\s*──\s*(?P<section>[^─\n]+?)\s*─+|LocaleKeys\.(?P<name>\w+)\s*:\s*(?P<value>\"(?:[^\"\\]|\\.)*\"|'(?:[^'\\]|\\.)*')",
        re.S,
    )
    for match in token.finditer(body):
        if match.group("section"):
            current = match.group("section").strip()
            continue
        name, raw = match.group("name"), match.group("value")
        value = bytes(raw[1:-1], "utf-8").decode("unicode_escape")
        key = keys.get(name, name)
        sections.setdefault(current, []).append((name, key, value))
    return sections


def swift_ident(name: str) -> str:
    return f"`{name}`" if name in SWIFT_KEYWORDS else name


def placeholders(value: str) -> list[str]:
    return list(dict.fromkeys(re.findall(r"@(\w+)", value)))


def to_format(value: str) -> str:
    # @wait → %@ positional, in order of first appearance.
    names = placeholders(value)
    out = value.replace("%", "%%")
    for index, name in enumerate(names, start=1):
        out = out.replace(f"@{name}", f"%{index}$@")
    return out


def main(localization_dir: str) -> None:
    src = Path(localization_dir)
    keys = load_keys((src / "locale_keys.dart").read_text())
    sections = parse_strings((src / "app_string.dart").read_text(), keys)

    catalog = {"sourceLanguage": "en", "version": "1.0", "strings": {}}
    lines = [
        "// Generated by scripts/seed_strings.py from the Flutter app, then hand-maintained.",
        "// Every user-facing string in the app. Features use `L10n.Section.key`; never a literal.",
        "// Keys map 1:1 to Resources/Localizable.xcstrings. Add Arabic there, not here.",
        "// swiftformat:disable all",
        "import Foundation",
        "",
        "public enum L10n {",
        "    static let bundle = LocalizedStringResource.BundleDescription.atURL(Bundle.module.bundleURL)",
        "",
    ]

    def emit(enum_name: str, entries: list[tuple[str, str, str]]):
        lines.append(f"    public enum {enum_name} {{")
        seen: set[str] = set()
        for name, key, value in entries:
            if name in seen:
                continue
            seen.add(name)
            names = placeholders(value)
            fmt = to_format(value)
            catalog["strings"][key] = {"localizations": {"en": {"stringUnit": {"state": "translated", "value": fmt}}}}
            escaped = fmt.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            if names:
                params = ", ".join(f"_ {n}: String" for n in names)
                args = ", ".join(names)
                lines.append(f"        public static func {swift_ident(name)}({params}) -> String {{")
                lines.append(
                    f'            String(format: String(localized: "{key}", defaultValue: "{escaped}", bundle: .module), {args})'
                )
                lines.append("        }")
            else:
                lines.append(
                    f'        public static let {swift_ident(name)} = LocalizedStringResource("{key}", defaultValue: "{escaped}", bundle: bundle)'
                )
        lines.append("    }")
        lines.append("")

    for section, entries in sections.items():
        emit(SECTION_ENUM.get(section, re.sub(r"\W", "", section.title())), entries)
    for enum_name, entries in IOS_ADDITIONS.items():
        emit(enum_name, [(n, k, v) for n, (k, v) in entries.items()])

    lines.append("}")
    L10N_SWIFT.write_text("\n".join(lines) + "\n")
    XCSTRINGS.parent.mkdir(parents=True, exist_ok=True)
    XCSTRINGS.write_text(json.dumps(catalog, indent=2, ensure_ascii=False, sort_keys=True) + "\n")
    total = sum(len(v) for v in sections.values()) + sum(len(v) for v in IOS_ADDITIONS.values())
    print(f"Seeded {total} strings in {len(sections) + len(IOS_ADDITIONS)} sections → {L10N_SWIFT.name}, {XCSTRINGS.name}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
